language: node_js
node_js:
- 9
before_script:
- npm install -g gulp-cli
script:
- gulp
- npm run coverage
cache:
  directories:
  - node_modules
env:
  global:
    secure: GZYtxTsAOu8YU+Wbx3FV+Cv2dR+86qjfvx/dmsLLnhTRnMA79LCatxvcW7Ig89ze6sS/LuNrcogv1ORdJBSMq60M19MjOC3QJbJ5oKN8C7iP4SnmWPquGW/x4ask2XgqYd7MSXyPJQ8VHcTJH37uU5B+IXEX4stR5gfBJ77x2Gka2bbhIyZXYVbJ7WGkCqXRgyJ1J/+RSFNk/G162n19fEFLB+USFIU0vsKXlJIIAYFC09AutFgP0TFaqJtJcbppNXc2JikV006YSGOBoy/HO2BWEdi9cmfzGIDJQ07fQv/NfVd5HZd8OiaBqN3yfDZDkflQ5tPuRV05phOojOCHAc7Ln4DNnB6hjYGmsxZVpNHyWP7zbsZraqeINPXjR86n2mwgCEdT8YkgTixMFJqwspBJp8dR6g8RXMJ5IT0WuT+f4Vaddestp9e/tbpmkdBhhWrHygiXlP1gbGrAMJgEOHL+LObBdGkzjDI2yPYLO4UZ7jVr3oXQ0AK+2y3jWe3JW+tmC514GX5dOVQevGC3Ml88CT7mH2bw5qJkBMock+Yc5X0ttU5poRTaEJm5g5+kdapi58a5ppb+Ao/kKyXeqciw0+nfYiEXtvLp0mLc/omTWZIpn0BZJJItOT6+gdshOh1IbHPbpuy5NF8Q8EMYuNRzgNfUpY4/FJKBxx6689A=
