language: node_js
node_js:
- 10
before_script:
- npm install -g gulp-cli gulp@4
script:
- gulp
- npm run coverage
cache:
  directories:
  - node_modules
env:
  global:
    secure: GZYtxTsAOu8YU+Wbx3FV+Cv2dR+86qjfvx/dmsLLnhTRnMA79LCatxvcW7Ig89ze6sS/LuNrcogv1ORdJBSMq60M19MjOC3QJbJ5oKN8C7iP4SnmWPquGW/x4ask2XgqYd7MSXyPJQ8VHcTJH37uU5B+IXEX4stR5gfBJ77x2Gka2bbhIyZXYVbJ7WGkCqXRgyJ1J/+RSFNk/G162n19fEFLB+USFIU0vsKXlJIIAYFC09AutFgP0TFaqJtJcbppNXc2JikV006YSGOBoy/HO2BWEdi9cmfzGIDJQ07fQv/NfVd5HZd8OiaBqN3yfDZDkflQ5tPuRV05phOojOCHAc7Ln4DNnB6hjYGmsxZVpNHyWP7zbsZraqeINPXjR86n2mwgCEdT8YkgTixMFJqwspBJp8dR6g8RXMJ5IT0WuT+f4Vaddestp9e/tbpmkdBhhWrHygiXlP1gbGrAMJgEOHL+LObBdGkzjDI2yPYLO4UZ7jVr3oXQ0AK+2y3jWe3JW+tmC514GX5dOVQevGC3Ml88CT7mH2bw5qJkBMock+Yc5X0ttU5poRTaEJm5g5+kdapi58a5ppb+Ao/kKyXeqciw0+nfYiEXtvLp0mLc/omTWZIpn0BZJJItOT6+gdshOh1IbHPbpuy5NF8Q8EMYuNRzgNfUpY4/FJKBxx6689A=
notifications:
  slack:
    secure: KtdGisJag+ihdULR76FJMbLA5kPucSdxUR6LftnzoixBdbtl89mAFheW3S7xIVh9FJQBF/g0AzWidTbcvE79uhGZnJ+W20miCokFyQHwKCffGpb7Ec8kDqMfl5nnhrB/lgp4UA/eo6NztnToYI07gJt3XRYaEHhmjNNh9GV1cg0U7Ie0tetk3ZkAVrmtWjpEEdJTowguL6oIyoDIZw1fB6m5T7zaWZSh5aRxsd+EElsTpTMSstBuk+BezPOJZOXTY5QykogNjsE+3X+q9aXvzrONz2I+JVb2PLbkziG/sZwuNRXaab/RsNwCrLQGA8ZEnWPTfpyKHXc6Rkqko4BB6ThiS7s/4oj2GIry9j9euHNbsHjR++k1QyfAAQtTllvsJ8Va1/oiTN4IB+2weq6PfT2dey+gmDwnDBSO9aaUlNO50Y8nPOHi2UMF2L7454d2idmk263dNrgtgNZ0RRq5xwRAPAo173EQKh2hiQYlptXoaRCiC7W83FlNo4so3X0T1F90D3oYHNKRMrsTEece4/ewPdLB96lTdou9zdd0I9x9PfgxWIjPBagOCExQEzLO3G2+YNQ+HXpmZdQiw9G82N3/N40hhaMTEf8HsW1opa+0m1+i8nGGP7BRpJLKpioqVZytH3HPC4GQH4FS/WznX7CkFumRbzfioBCRFkdtUTk=
