language: node_js
node_js:
- 10
before_script:
- npm install -g gulp-cli gulp@4
script:
- gulp
- npm run coverage
cache:
  directories:
  - node_modules
env:
  global:
    secure: BvdNzRKvhEWacIrfK7xBF9qZ/5jDSeo/zGM3HwnnGo/fgXabWXY1QJ031ypGPJpeobya0cPTws/i+XdHK80k06CUoq9k+yXmNq+tRhaKFlDXLJreHspdgCzFtUvxg0DtlESMgTMcQgyEQs2BiwqAnPUtabY/FJTn5Dl1RcH+8OX4sQiAuOvG/2SjM1cq8S4Ul5X3U1huU4lSkZvBh5Rxx0fhYq3Lz9fWZa/hDPJG38FdAg6qduPWxf9axbbhk1cseb6GFobn7r9qfO3RT0TgOUWaCAexrxdMK2nDCT4XStAPK+nF2Z9caLT2Aws4MOlQIB2cV9PwINzIrAG3NDD15LKGCKFsvBUX+BRDEfsIsqPIa4pK4grIeIPA1DWt2bIwOPDn/vLiHQYp0HuAI3urwg87bscBDjJY1rdL0JI9TSerRV+sQg6cnkRrMs3//x0O+L6NucdppELtPIH9fJbm5N77OXOXcsLmHm4tY/Qi9KbaTtEQnlWtFC+0tosiA/NC+4Ear1PZrN5mrZTg6VPRcxZSAm464StcO8iZWTGukUG47mEBfQ4/46B4V6TUOExs6vuhICd2HTKU80nGdtR1pUL3/iwyBquLSflt1EVXFzNd76+CyBjB4DwOu59Wb8di0dxACqTY9aKnpUiJ5Agk9OLOjvNlIMONBGDaqTW6cEg=
notifications:
  slack:
    secure: M1vJTWT5f+cF7AkmXxBwNKAa+KCeCnWZGcz0hDVR37L/upB7nl0jjFUgMacRwW4eQD7zrPNKqDnFuP41DIaKZFZUKLC/N2FvhlrJY9WBqnhBSOMXmBaY68eu7pjp+wuuz9RMED4kl6RuEbxMk9riGpWqHmnOjKKDKLPUN/4S2ThKGc6cIbaSx3fZYRxNk80XV2vN+gzVZif+9Vxl9fizOtZJ2kFMCQZk1eiiMUd2apaMSRv/uFNIkz7F4qC3IVk3+Y9o9odp65kKFHfL5s4Lj7jYj7c2TV4tHcjvJyG+2bpQ/U9KpdnJmvELxtA3of431UbZRyw+dsRd3DX/7A2Y8KjyEErILto1wE/2bWPLQsDsbOW6gGAXn6/azJrD+dRbhTaCR6ETMdfajK7+LGbLN4ocM2TsaAdDwDmfsRQDOOFKQPAzgWf96ghiAQRbQcfaYaz3AZGDtz8HWsGhmROy+tXch5vcvrG0ZI7kQVAXL6ijdynrYax3z1THFLl4ywHZ2fb+QSp4Xb4WVkKJobbRxIFAI71tDJMeXn8Wmnb161LKo6XBZK2eEShNkOu9Ar0eDDwC9X8Aw8qrMx1sMZHkTyCKgsPTPFraaCFcSyAm0Xji4uuxept1XF58x5wiyy1WyP4xi0kfxSPAxORmFy3a7JriFKIQGtCO98JrUIfHwDQ=
deploy:
- provider: npm
  api_key:
    secure: toI4MsgjHNico8rKJAyRM36+mvtCidYfthReP+P1xhfpH5C+/SRxC4GXpWPc7vtx8jWTEekvVeZ2jslY0nPBwH1AZhMo8lV0zSgSsSdAelWKGnsM2DBgznmK5u96WHYzgQT2MWfr2B4gk9nrmPDKpcelcChT58CkPMKsb+sWa8U/pdVA/S4wvRKbP64XLbIRWWSz7TgrJLjDAm0SY2OubbYLcliO8AIdV5GV1+22EQT9FMxEnQ5PE99KV4KPpLzyEYTSDIHMxpT5LgC+xxyY1QD40kJruUIrAf0b+2p3XtmLSYt5xMOE1tg+6jDui/q0YVKp3DJin++WuMbZ8DeTz6BbzfdqgTM5Vqqw1RDG+GAVqUWK+sbKO0VwXKk1yiXB/Berrgv2gg7LptmpMwKHV0Qk/NIG7SSrCwr8oHYA4iWOVcp4C2wZ9wrKeelxSWoThS1Y0mj0BEzhj+jF6J9oKwYsrDOLeSiqkDw9Hi1eHyaQKEvhRqpwuOCGSGXoHG9atIxQcDhA+ERw1pAJmlCG2nMXKcuMuYF/jkr5OfqIpv7lR7dweeKemJCPPGEajYDqhORgo6KHdjvpEKpSkoPAXQ3D2x8hUDQI6J+c4fkD+UczqQGJRO+4flEC5axOQypBhpckKP4bxgSpTFl8Yn83+0OmesjJM2Yn5pwcCQHykOc=
  email:
    secure: d/O8qJy/ZzFsACqVpE5Wh1nMXcmONm5JqLyLY5SvjqYHUGVdLzZ860eg4b0yz+CFVej5ms/qhkkn8w0TJugcxX9Y9DrCh+TNJ0LHlI8x1T9WucjlKMJWoZx0kbwY93Vpn+WwrRKILfak9IvumB+QQ0D1gWV9bo1p5KdW4ndTykTQotBYYIH7fZScJqKCuvjxLtUoU0VnJjx+AtcxJDTNNeSSXNTyWC1AHUJxvNr3AYZd7zbVQkQ7/kM02A9xav6/bA0ban5Nrb9SyES6BBNKftb22P/YoPFsS7ik/0xwZek8LEaeSwPrF9iasngXotPfnuP8WPHz2Iod3vByMwM0ku+bdTczN2JPI8c7eS4NbWP/enXmNrSZWr97I9ucTLktxzZuyKek7H+Dbg+R2AZ9OUqd4cExggDLUBxyiXPctpewo2IlOiNy1D8Bf+K5aDBWlz+s80FkYtSDLA0zTwdrTM8ZS3e9Pz7wUUcjoL/dIiWpE2sFDHMg9RjcMcqoaIWTF/7mGFKx8PgbSfJtvUtKBM+YIn1st90cuI6tX2odqFP9/UOQxYwbgSkELcdPSY7rb8Hn1X9Sh/fP2SR3+UJr7YioW9sBgMj5lG1XkxbBABG/JEP22wtu4eGfYOllOxuV6oT+2L8O5NWWDrogY1qJmh/P/EBF4k6Zr6ji6f+QbPQ=
  on:
    branch: master
